"use client";

import jsPDF from "jspdf";

import usePortfolio from "@/hooks/usePortfolio";
import usePortfolioAnalytics from "@/hooks/usePortfolioAnalytics";

import { formatCurrency } from "@/lib/formatters";

export default function PortfolioReport() {
  const { portfolio } = usePortfolio();

  const { analytics } =
    usePortfolioAnalytics();

  function generatePortfolioReport() {
    if (!analytics) {
      alert("Portfolio is loading.");
      return;
    }

    const doc = new jsPDF();

    let y = 20;

    // ===============================
    // Header
    // ===============================

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);

    doc.text("QUANTIVOX AI", 105, y, {
      align: "center",
    });

    y += 8;

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    doc.text(
      "AI Powered Stock Decision Support System",
      105,
      y,
      {
        align: "center",
      }
    );

    y += 15;

    doc.line(15, y, 195, y);

    y += 10;

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");

    doc.text("Portfolio Report", 15, y);

    y += 12;

    const generatedDate =
      new Date().toLocaleString();

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    doc.text(
      `Generated On : ${generatedDate}`,
      15,
      y
    );

    y += 12;

    doc.line(15, y, 195, y);

    y += 10;

    // ===============================
    // Summary
    // ===============================

    doc.setFontSize(15);

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.text(
      "Portfolio Summary",
      15,
      y
    );

    y += 12;

    const investment =
      formatCurrency(
        analytics.totalInvestment,
        "INR"
      );

    const currentValue =
      formatCurrency(
        analytics.totalCurrentValue,
        "INR"
      );

    const profit =
      formatCurrency(
        analytics.totalProfitLoss,
        "INR"
      );

    doc.setFontSize(11);
    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.text(
      `Total Holdings : ${portfolio.length}`,
      15,
      y
    );

    y += 8;

    doc.text(
      `Investment : ${investment.primary}`,
      15,
      y
    );

    y += 8;

    doc.text(
      `Current Value : ${currentValue.primary}`,
      15,
      y
    );

    y += 8;

    doc.text(
      `Profit / Loss : ${profit.primary}`,
      15,
      y
    );

    y += 15;

    doc.line(15, y, 195, y);

    y += 10;

    // ===============================
    // Holdings
    // ===============================

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(15);

    doc.text(
      "Holdings",
      15,
      y
    );

    y += 12;

    doc.setFontSize(11);

    analytics.holdings.forEach(
      (holding) => {
        const current =
          formatCurrency(
            holding.currentPrice,
            holding.currency
          );

        const pnl =
          formatCurrency(
            holding.profitLoss,
            holding.currency
          );

        doc.setFont(
          "helvetica",
          "bold"
        );

        doc.text(
          holding.symbol,
          15,
          y
        );

        doc.setFont(
          "helvetica",
          "normal"
        );

        y += 6;

        doc.text(
          `Company : ${holding.company}`,
          20,
          y
        );

        y += 6;

        doc.text(
          `Quantity : ${holding.quantity}`,
          20,
          y
        );

        y += 6;

        doc.text(
          `Current Price : ${current.primary}`,
          20,
          y
        );

        y += 6;

        doc.text(
          `Profit / Loss : ${pnl.primary}`,
          20,
          y
        );

        y += 10;

        if (y > 260) {
          doc.addPage();
          y = 20;
        }
      }
    );

    y += 10;

    doc.line(15, y, 195, y);

    y += 10;

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
      "Disclaimer:",
      15,
      y
    );

    y += 6;

    doc.text(
      "This report is generated by Quantivox AI for educational purposes only.",
      15,
      y
    );

    doc.save(
      "Quantivox_Portfolio_Report.pdf"
    );
  }

  return (
    <button
      onClick={
        generatePortfolioReport
      }
      className="rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white transition hover:bg-blue-700"
    >
      Generate Portfolio Report
    </button>
  );
}